"""add day hour

Revision ID: 28ed41a62198
Revises: 4a1879b86807
Create Date: 2026-04-29 13:06:10.457153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ed41a62198'
down_revision: Union[str, Sequence[str], None] = '4a1879b86807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('day', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'hour')
    op.drop_column('classes', 'day')
    # ### end Alembic commands ###
